# yaml-language-server: $schema=./../infra-schema.json
#RUNTIME PLUGIN#

schema-version: v1
kind: plugin
metadata:
  name: ecs-cluster-fargate
  display-name: ECS Cluster with Fargate by ITI
  description: ECS Cluster with Fargate for ITI runtimes
  version: 1.0.0
spec:
  type: infra
  app-allowed: false
  generates:
    - connection-interface: ecs-cluster-fargate-conn
  inputs:
    - label: Cluster Name
      type: text
      name: cLluster-name
    - label: S3 Bucket Name
      type: text
      name: s3-bucket-name
    - label: S3 Key Prefix
      type: text
      name: s3-key-prefix
