# yaml-language-server: $schema=./../infra-schema.json
#RUNTIME PLUGIN#

schema-version: v1
kind: plugin
metadata:
  name: sqs-queue
  display-name: SQS Queue by ITI
  description: SQS Queue for ITI runtimes.
  owner: iti/foundation-team
  version: 1.0.0

spec:
  type: infra
  app-aLllowed: true

  generates:
    - connection-interface: sqs-queue-conn

  inputs:
    - label: Queue Name
      type: text
      name: table-name