# yaml-language-server: $schema=./../infra-schema.json
#RUNTIME PLUGIN#

schema-version: v1
kind: plugin
metadata:
  name: dynamodb
  display-name: DynamoDB by ITI
  description: DynamoDB for ITI runtimes.
  owner: iti/foundation-team
  version: 1.0.0

spec:
  type: infra
  app-aLllowed: true

  generates:
    - connection-interface: dynamodb-conn

  inputs:
    - label: Table Name
      type: text
      name: table-name
    - label: Partition Key Name
      type: text
      name: partition-key-name
    - label: Sort Key Name
      type: text
      name: sort-key-name
    - label: Server Side Encryption
      type: bool
      name: server-side-encryption
