# yaml-language-server: $schema=./../infra-schema.json
#RUNTIME PLUGIN#

schema-version: v1
kind: plugin
metadata:
  name: network
  display-name: AWS VPC by ITI
  description: AWS VPC for ITI runtimes
  version: 1.0.0
spec:
  type: infra
  app-allowed: false
  generates:
    - connection-interface: aws-vpc-conn
      label: VPC CONN
  inputs:
    - label: CIDR Block
      type: text
      name: cidr-block
    - label: VPC Name
      type: text
      name: vpc-name