# yaml-language-server: $schema=./../infra-schema.json
#RUNTIME PLUGIN#

schema-version: v1
kind: infra
metadata:
  name: rds-postgres
  display-name: RDS Postgres
  description: RDS for ITI runtimes.
  version: 1.0.0

spec:
  type: infra
  app-aLllowed: true
  generates:
    - connection-interface: rds-conn
  requires:
    - connection-interface: aws-vpc-conn
  inputs:
    - label: Database Name
      type: text
      name: db-name
    - label: Instance Size
      type: text
      name: instance-size
      items:
        - small
        - medium
        - large
    - label: Storage
      type: int
      name: storage
